project_name: gituser

before:
  hooks:
    - go mod tidy

builds:
  - binary: gituser
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - files:
      - LICENSE
      - README.md
  # If you want to use replacements in the archive name:
  # name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: gituser
    homepage: https://github.com/lucasnevespereira/homebrew-tools
    tap:
      owner: lucasnevespereira
      name: homebrew-tools
      branch: main

# modelines
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
