version: 2
project_name: gituser
before:
  hooks:
    - go mod tidy
builds:
  - binary: gituser
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
release:
  prerelease: auto
universal_binaries:
  - replace: true
archives:
  - files:
      - LICENSE
      - README.md
snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
checksum:
  name_template: 'checksums.txt'
brews:
  - name: homebrew-tools/gituser
    homepage: https://github.com/lucasnevespereira/homebrew-tools
    commit_author:
      name: lucasnevespereira
      email: pereiraneveslucas@gmail.com

# modelines
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
