name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Update AppVersion in utils.go
        run: |
          TAG_NAME=${GITHUB_REF/refs\/tags\//}
          sed -i "s/^const AppVersion =.*/const AppVersion = \"$TAG_NAME\"/" utils/const.go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
